---
title: "Wikiparfum scraping"
output: html_notebook
---

```{r}
library(xml2)
library(plyr)
library(rvest)
library(tidyverse)
library(readr)
```

```{r}
parfum <- read_html("https://web.archive.org/web/20241117232438/https://www.wikiparfum.com/en/fragrances/wood-sage-sea-salt-2024")
```

```{r}
parfum %>% 
  html_element(".flex-wrap") %>% 
  html_children() %>% 
  html_text()
```
```{r}
parfum2 <-  c("https://web.archive.org/web/20241117232438/https://www.wikiparfum.com/en/fragrances/wood-sage-sea-salt-2024")
fragrence2 <- tibble(URL = parfum2) %>% 
   mutate(HTML = map(URL, read_html))


#fragrence2 %>%   
#mutate(ing =  
  #html_element(".flex-wrap") %>% 
  #html_children() %>% 
  #html_text())
```

```{r}
fragurls <- read_lines("https://www.wikiparfum.com/fragrances_sitemap_en_0.xml") %>% 
  str_subset("<loc>https://.+/en/")
```

```{r}
set.seed(300)
fragurls <- sample(fragurls, 300)
fragurls
```


```{r}
read_lines("~/Downloads/fragrances_sitemap_en_0.xml") %>% 
  str_subset("<loc>https://.+/en/") %>% 
  

fraglist <- read_xml("https://www.wikiparfum.com/fragrances_sitemap_en_0.xml")

fraglist %>% 
  xml_children() %>% 
  head() %>% 
  xml_find_all("//loc")

library(xmlconvert)
#xml_to_df(fraglist)

```



```{r}
fragranceURLs <- c("https://web.archive.org/web/20241117232438/https://www.wikiparfum.com/en/fragrances/wood-sage-sea-salt-2024")
fragranceURLs2 <- c("https://web.archive.org/web/20240508220144/https://www.wikiparfum.com/en/fragrances/hypnotic-poison-eau-de-toilette-1/")

fragrence <- tibble(URL = fragranceURLs) %>% 
  mutate(HTML = map(URL, read_html))

fragrence2 <- tibble(URL = fragranceURLs2) %>% 
  mutate(HTML = map(URL, read_html))
```

```{r}
fragrence %>% pull(ingredients, frag.name)
 
```


```{r}
fragrence <- fragrence %>% 
  # almost correct element
  mutate(frag.name = map_chr(HTML, ~.x %>% 
                     html_element("h1") %>% 
                            html_text())) %>% 
                        
  # correct element
  mutate(ingredients = map(HTML, ~ .x %>% 
                              html_element(".flex-wrap") %>% 
                              html_children() %>% 
                              html_text())) %>% 
# correct element, need to remove "info"
mutate(price = map(HTML, ~ .x %>%
  html_element(xpath="//dt[text()='price']/following-sibling::dd/span") %>% 
  html_elements(".text-black") %>% 
  html_text() %>% 
  str_flatten())) %>% 
  
 # almost correct element. needs some tidying
mutate(olfactive.class = map_chr(HTML, ~.x %>% 
                     html_element(".p-3") %>% 
                            html_text())) %>% 
# incorrect 
mutate(world.clasif = map_chr(HTML, ~ .x %>%
  html_element(xpath="//dt[contains(text(), 'of the world')]/following-sibling::dd") %>% 
  html_text())) %>%  
#Correct path!
  mutate(description = map_chr(HTML, ~.x %>% 
                     html_element(".pb-3") %>% 
                            html_text())) %>% 
 #correct path
   mutate(origin = map_chr(HTML, ~.x %>% 
                     html_element(".py-5") %>% 
                            html_text())) %>% 
  # correct path 
  mutate(gender = map_chr(HTML, ~.x %>% 
                     html_element(".border-gold200:nth-child(2)") %>% 
                            html_text())) %>% 
  # correct path
    mutate(year = map_chr(HTML, ~.x %>% 
                     html_element(".border-gold200:nth-child(3)") %>% 
                            html_text())) %>%
  
  # correct path
    mutate(concepts = map_chr(HTML, ~.x %>% 
                     html_element(".border-gold200~ .border-gold200+ .border-gold200") %>% 
                            html_text())) %>% 
  # incorrect path
  mutate(perfumer = map_chr(HTML, ##perfumer
~ .x %>%
  html_element(xpath="//dt[text()='perfumer']/following-sibling::dd") %>% 
  html_text()))  


```

```{r}
print(fragrence)
```
```{r}
fragrence2 <- fragrence2 %>% 
  # almost correct element
  mutate(frag.name = map_chr(HTML, ~.x %>% 
                     html_element("h1") %>% 
                            html_text())) %>% 
                        
  # correct element
  mutate(ingredients = map(HTML, ~ .x %>% 
                              html_element(".flex-wrap") %>% 
                              html_children() %>% 
                              html_text())) %>% 
# correct element, need to remove "info"
mutate(price = map_chr(HTML, ~ .x %>%
  html_element(xpath="//dt[text()='price']/following-sibling::dd/span") %>% 
  html_elements(".text-black") %>% 
  html_text() %>% 
  str_flatten()))  %>% 
  
 # almost correct element. needs some tidying
mutate(olfactive.class = map(HTML, ~.x %>% 
                     html_element(".p-3") %>% 
                            html_text())) %>% 
# incorrect 
mutate(world.clasif = map(HTML, ~.x %>%
  html_element(xpath="//dt[contains(text(), 'of the world')]/following-sibling::dd") %>% 
  html_text())) %>%  
#Correct path!
  mutate(description = map(HTML, ~.x %>% 
                     html_element(".pb-3") %>% 
                            html_text())) %>% 
 #correct path
   mutate(origin = map(HTML, ~.x %>% 
                     html_element(".py-5") %>% 
                            html_text())) %>% 
  # correct path 
  mutate(gender = map(HTML, ~.x %>% 
                     html_element(".border-gold200:nth-child(2)") %>% 
                            html_text())) %>% 
  # correct path
    mutate(year = map(HTML, ~.x %>% 
                     html_element(".border-gold200:nth-child(3)") %>% 
                            html_text())) %>%
  
  # correct path
    mutate(concepts = map(HTML, ~.x %>% 
                     html_element(".border-gold200~ .border-gold200+ .border-gold200") %>% 
                            html_text())) %>% 
  # incorrect path
  mutate(perfumer = map(HTML, ~.x %>% 
                     html_element(".pt-5.gap-4") %>% 
                            html_text())) 
```

```{r}
print(fragrence2)
```


```{r}
fragrence %>% 
  mutate(parfum %>% 
  html_element(".flex-wrap") %>% 
  html_children() %>% 
  html_text())
```



# Session info

```{r}
sessionInfo()
